# Default values for reportportal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: reportportal.local
      paths: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

api:
  image:
    repository: reportportal/service-api
    tag: 5.0.0

ui:
  image:
    repository: reportportal/service-ui
    tag: 5.0.0

# Add configurations for other ReportPortal services (e.g., indexer, migrations)
