apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reportportal.fullname" . }}
  labels:
    {{- include "reportportal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "reportportal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "reportportal.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URL
              value: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/reportportal"
            - name: POSTGRES_USERNAME
              value: "reportportal"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgresql-password
            - name: OPENSEARCH_URL
              value: "http://{{ .Release.Name }}-opensearch:9200"
            - name: RABBITMQ_URL
              value: "amqp://reportportal:reportportal@{{ .Release.Name }}-rabbitmq:5672"
            - name: S3_ENDPOINT
              value: "{{ .Values.s3.endpoint }}"
            - name: S3_ACCESS_KEY
              value: "{{ .Values.s3.accessKey }}"
            - name: S3_SECRET_KEY
              value: "{{ .Values.s3.secretKey }}"
            - name: S3_BUCKET_NAME
              value: "{{ .Values.s3.bucketName }}"
            - name: S3_REGION
              value: "{{ .Values.s3.region }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
