apiVersion: v1
kind: Service
metadata:
  name: {{ include "reportportal.fullname" . }}-api
  labels:
    app: {{ include "reportportal.name" . }}
    chart: {{ include "reportportal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "reportportal.name" . }}
    release: {{ .Release.Name }}
    component: api
